
POST localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzYxNjI1MzU2LCJ1c2VySWQiOjR9.roBZDWWP16cKBWE3tdP7htK9pw9RW0Lf7fydAR5_8vI

{
  "name" : "Test event2",
  "description": "Test event!!",
  "location": "A test location",
  "dateTime":"2025-01-01T15:30:00.000Z"
}