DELETE http://localhost:8080/events/4
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzYxNTUyNzI0LCJ1c2VySWQiOjJ9.V5L7lBoZ6zGJipGklb16RcVpYvK6arJo2hMr92cJ4Lw
