POST http://localhost:8080/events/1/register
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzYxNjI1MzU2LCJ1c2VySWQiOjR9.roBZDWWP16cKBWE3tdP7htK9pw9RW0Lf7fydAR5_8vI